- hosts: local
  become: true
  tasks:
    - include: tasks/software.yaml
- hosts: local
  become: false
  tasks:
    - include: tasks/zsh.yaml
    # - include: tasks/gnome.yaml
- hosts: local
  become: true
  tasks:
    - include: tasks/sudo.yaml