# update system
- name: SOFTWARE - update apt repositories and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: SOFTWARE - apt upgrade all
  apt: upgrade=dist force_apt_get=yes

# install apt-transport-https
- name: SOFTWARE - insall apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: true

# add keys and additional repositories
- name: SOFTWARE - Add signing keys - chrome browser
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
- name: SOFTWARE - Add chrome browser repository
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
- name: SOFTWARE - Add signing keys - vscode
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
- name: SOFTWARE - Add vscode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: code
- name: SOFTWARE - Add mainline ppa
  apt_repository:
    repo: 'ppa:cappelikan/ppa'

# install packages from repositories
- name: SOFTWARE - Install tools from repositories
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - curl
    - snapd
    - fonts-powerline
    - gnome-tweaks
    - google-chrome-stable
    - htop
    - wget
    - zsh
    - mainline
    - smbclient
    - cifs-utils
    - python3-smbc
    - ncdu
    - texstudio
    - texlive
    - texlive-latex-extra
    - code
- name: SOFTWARE - Remove dependencies that are no longer required
  apt:
    autoremove: yes

# install snap packages
- name: SOFTWARE - Install Snap packages
  snap:
    name: "{{ item }}"
  loop:
    - authy
    - remmina
    - slack
    - spotify
    - vlc
    - signal-desktop