# configure zsh shell
- name: ZSH - Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
- name: ZSH - Copy .zshrc template config
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
- name: ZSH - Install powerlevel10k theme for zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
- name: ZSH - Set powerlevel10k theme in .zshrc
  ansible.builtin.replace:
    path: ~/.zshrc
    regexp: 'ZSH_THEME=".+"'
    replace: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
- name: ZSH - Install zsh syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
- name: ZSH - Install zsh zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
- name: ZSH - Set zsh plugins in .zshrc
  ansible.builtin.replace:
    path: ~/.zshrc
    regexp: 'plugins=\(.+\)'
    replace: "plugins=(git zsh-syntax-highlighting zsh-autosuggestions)"
- name: ZSH - Create ~/.fonts directory
  ansible.builtin.file:
    path: ~/.fonts
    state: directory
- name: ZSH - Font MesloLGS NF Regular.ttf for powerlevel10k zsh theme
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    dest: "~/.fonts/MesloLGS NF Regular.ttf"
- name: ZSH - Font MesloLGS NF Bold.ttf for powerlevel10k zsh theme
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    dest: "~/.fonts/MesloLGS NF Bold.ttf"
- name: ZSH - Font MesloLGS NF Italic.ttf for powerlevel10k zsh theme
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    dest: "~/.fonts/MesloLGS NF Italic.ttf"
- name: ZSH - Font MesloLGS NF Bold Italic.ttf for powerlevel10k zsh theme
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
    dest: "~/.fonts/MesloLGS NF Bold Italic.ttf"
